config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :bikes
  resources :manufacturers
  resources :bikers

  get "/signup", to: "bikers#new", as: "signup"
  get "/login", to: "login#new", as: "login_path"
  post "/login", to: "login#verify"
  get "/logout", to: "login#logout", as: "logout_path"
  get "/bikes/:id/images/:id", to: "bikes#images", as: "bikes_image"
  delete 'bikes/:id/images/:id', to: "bikes#destroyImage", as: "bikes_image_destroy"

  root to: "login#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :bike
  belongs_to :biker
  has_many :trip_comments
  has_many :bikers, through: :trip_comments

  has_many_attached :images
  accepts_nested_attributes_for :trip_comments #, :reject_if => lambda { |c| c[:comment].blank? }
  #accepts_nested_attributes_for :images 

  def trip_comments_attributes=(trip_comment_attributes)
    trip_comment_attributes.values.each do |trip_comment_attributes|
      if trip_comment_attributes["comment"].present?
        trip_comment = TripComment.create(trip_comment_attributes)
        self.trip_comments << trip_comment
      end
    end
  end

  
  # def image_attributes=()
  #   image_attributes.values.each do |image_attribute|
  #     if image_attributes["image"].present?
  #       image_attribute = TripComment.create(trip_comment_attributes)
  #       self.trip_comments << trip_comment
  #     end
  #   end
  # end

  def newest_comments
    self.trip_comments.order(updated_at: :desc)
  end

  def timestamp
    super.in_time_zone(timezone) if super
  end

  # def artist_name=(name)
  #   self.artist = Artist.find_or_create_by(name: name)
  # end

  # def artist_name
  #   if artist
  #     self.artist.name
  #   end
  # end


end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :redirect_user

    def index
        @trips = Trip.all
    end
    
    def new
        #code to check for user session[:id]
        #Time.zone = current_user.time_zone if logged_in?
        @trip = Trip.new
        @biker = Biker.find(session[:user_id])
        @bikes = @biker.bikes   
    end

    def show        
        @trip = Trip.find(params[:id])           
        @images = @trip.images  
    end

    def edit
        byebug
    end

    def create        
        @trip = Trip.new(trip_params)        
        if(@trip.save)
            redirect_to trip_path(@trip)
        else
            render :new
        end
    end

    def update
        @trip = Trip.find(params[:id])            
        @trip.update(trip_params)
        if(@trip)
            redirect_to @trip
        else
            render :show
        end
    end

    private

    def trip_params
        params.require(:trip).permit(
            :biker_id,
            :bike_id,
            :name,
            :start_city,
            :dest_city,
            :distance_miles,
            :start_date,
            :end_date,            
            images: [],
            trip_comments_attributes: [:comment, :biker_id]
        )
    end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/index.html.erb
<ul>
<% @trips.each do |trip| %>
    <li><%= link_to(trip.name, trip_path(trip.id)) %>     |     <%= trip.distance_miles %> miles     |     <%= trip.biker.biker_full_name %>     |     <%= trip.start_date %></li>
<% end %>
</ul>

app/views/trips/new.html.erb
<h1>New Trip for <%= session[:first_name] %> </h1>

<%= form_for @trip do |f| %>
    <%= f.hidden_field :biker_id, value: session[:user_id] %>
    <%= f.label :name %><br>
    <%= f.text_field :name %><br>
    <%= f.label :bike_id %><br>
    <%= f.collection_select :bike_id,  @bikes, :id, :bike_name %><br>
    <%= f.label :start_city %><br>
    <%= f.text_field :start_city %><br>
    <%= f.label :dest_city %><br>
    <%= f.text_field :dest_city %><br>
    <%= f.label :distance_miles %><br>
    <%= f.number_field :distance_miles, step: 0.1 %><br>
    <%= f.label :start_date %><br>
    <%= f.datetime_select  :start_date %><br>
    <%= f.label :end_date %><br>
    <%= f.datetime_select :end_date %><br><br>

    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
    <br><br>
    
    <%= f.submit %>
<% end %>

app/views/trips/show.html.erb
<h2>Trip: <%= @trip.name %></h2>
<h3>Rode by: <%= link_to(@trip.biker.biker_full_name, biker_path(@trip.biker.id)) %></h3>

Bike name: <%= @trip.bike.bike_name %><br>
Bike manufacturer: <%= @trip.bike.manufacturer.name %><br>
Distance: <%= @trip.distance_miles %>miles<br>

<h3>Images</h3>
<% @trip.images.each do |image| %>
    <%= image_tag(image)%>
<% end %>

<br><br>

<%= form_for @trip do |f| %>
    <%= f.fields_for :trip_comments, @trip.trip_comments.build do |trip_comment_fields| %>        
        <%= trip_comment_fields.text_area :comment %>        
        <%= trip_comment_fields.hidden_field :biker_id, value: session[:user_id] %><br>
    <% end %>
    <%= f.submit "Add a comment"%>
<% end %>

<br>
<br>

<% @trip.newest_comments.each do |tc| %> 
    <% if (tc.id != nil) %>  
        <li><%= link_to(tc.biker.biker_full_name, biker_path(tc.biker)) %>|<%= " :#{tc.updated_at}" %> <br> Says"<%= tc.comment %>"</li><br>
    <% end %>
<% end %>