config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :bikes
  resources :manufacturers
  resources :bikers

  get "/signup", to: "bikers#new", as: "signup"
  get "/login", to: "login#new", as: "login_path"
  post "/login", to: "login#verify"
  get "/logout", to: "login#logout", as: "logout_path"
  get "/bikes/:id/images/:id", to: "bikes#images", as: "bikes_image"
  delete 'bikes/:id/images/:id', to: "bikes#destroyImage", as: "bikes_image_destroy"

  root to: "login#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/biker.rb
class Biker < ApplicationRecord
    has_many :bikes
    has_many :trips
    has_many :comments

    validates :first_name, format: {with: /\D+/, message: " can only contain alpha characters."}, allow_blank: true
    validates :last_name, format: {with: /\D+/, message: " can only contain alpha characters."}, allow_blank: true
    validates :user_name, format: {without: /\s+/, message: " can not have spaces."} 
    validates :user_name, presence: true
    validates :user_name, uniqueness: true

    has_secure_password

    def biker_full_name
        "#{self.first_name} #{self.last_name}"
    end

    def total_trip_distances
        self.trips.map{|trip| trip.distance_miles.to_f.round(2)}.reduce{|sum, next_i| sum + next_i}                
    end

    def trips_newest_first
        self.trips.order(updated_at: :desc)
      end
end

app/controllers/bikers_controller.rb
class BikersController < ApplicationController
        before_action :redirect_user, except: [:new, :create]
        before_action :get_biker, only: [:show, :edit, :update]

    def show     
        @trips = @biker.trips_newest_first        
    end

    def new
        @biker = Biker.new
    end

    def create
        
        @biker = Biker.new(biker_params)
        if(@biker.save)            
            session[:user_id] = @biker.id
            session[:first_name] = @biker.first_name
            session[:last_name] = @biker.last_name
            session[:biker_full_name] = @biker.biker_full_name                       
            redirect_to biker_path(@biker)
        else            
            puts @biker.errors
            render :new
        end
    end

    def edit        
    end

    def update
        if(@biker.update(biker_parmas))
            redirect_to @biker
        else
            render :edit
        end
    end
    
    private

    def biker_params
        params.require(:biker).permit(            
            :first_name,
            :last_name,
            :home_city,
            :user_name,
            :password, 
            :password_confirmation
        )
    end

    def get_biker        
        @biker = Biker.find(params[:id])        
    end

end

app/helpers/bikers_helper.rb
module BikersHelper
end

app/views/bikers/edit.html.erb
<% if (@biker.errors.any?) %>
<ul>    
     <% @biker.errors.full_messages.each do |msg| %>
    <span class="error_text">
    <li> <%= msg %></li>
     </span>
    <% end %>
</ul>
<% end %>

<p><%= image_tag("biking-image.jpg",width: '400px') %>

<h2>Edit Your Bike Account</h2>
<%= form_for @biker do |f| %>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %><br><br>
    <%= f.label :biography %><br>
    <%= f.text_area :biography %><br>
    <%= f.submit %>
<% end %>
</p>

app/views/bikers/new.html.erb
<% if (@biker.errors.any?) %>
<ul>    
     <% @biker.errors.full_messages.each do |msg| %>
    <span class="error_text">
    <li> <%= msg %></li>
     </span>
    <% end %>
</ul>
<% end %>


<p><%= image_tag("biking-image.jpg",width: '400px') %>

<h2>Create Your Bike Account</h2>
<%= form_for @biker do |f| %>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %><br><br>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %><br><br>
    <%= f.label :home_city %><br>
    <%= f.text_field :home_city %><br><br>
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %><br><br>
    <%= f.label :password %><br>
    <%= f.password_field :password %><br>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>
    <%= f.submit %>
<% end %>
</p>

app/views/bikers/show.html.erb
<h3>Profile for <%= @biker.first_name %> </h3>
<%= link_to("Signout", logout_path_url ) %><br>
<%= link_to("All Trips", trips_path) %>
<h3>Name</h3>
<%= @biker.biker_full_name %><br>

<h3>User name</h3>
<%= @biker.user_name %><br>

<h3>Home City</h3>
<%= @biker.home_city %><br>

<h3>Bikes</h3> 
<% @biker.bikes.each do |bike| %>
    Name:<%= link_to(bike.bike_name, bike_path(bike)) %><br>
    Manfacturer: <%= "#{bike.manufacturer.name}"%><br>
    Bike Type: <%= "#{bike.bike_type.to_s}"%><br>
    Stolen: <%= "#{bike.stolen.to_s}"%><br>
<% end %>
<br>
<%= link_to("Create Bike", new_bike_path(@biker))%><br>
<%= link_to("Manufacturers Index", manufacturers_path) %><br>


<h3><%=@biker.first_name %>'s Trips</h3> <%= link_to("Create Trip", new_trip_path(@biker))%><br>
Total Distance: <%= @biker.total_trip_distances %> miles<br><br>


<% @trips.each do |trip| %>
    <li><%= link_to(trip.name, trip_path(trip.id)) %>     |     <%= trip.distance_miles %> miles     |     <%= trip.biker.biker_full_name %>     |     <%= trip.start_date %></li>
<% end %>