config/routes.rb
Rails.application.routes.draw do
  resources :trips
  resources :bikes
  resources :manufacturers
  resources :bikers

  get "/signup", to: "bikers#new", as: "signup"
  get "/login", to: "login#new", as: "login_path"
  post "/login", to: "login#verify"
  get "/logout", to: "login#logout", as: "logout_path"
  get "/bikes/:id/images/:id", to: "bikes#images", as: "bikes_image"
  delete 'bikes/:id/images/:id', to: "bikes#destroyImage", as: "bikes_image_destroy"

  root to: "login#new"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :biker
  belongs_to :manufacturer  
  has_many_attached :images


  # def images=(image)    
  #   byebug
  #   #new_image = Image.create(image)
  #   #self.images.build(image.as_json)
  # end

    # def trip_comments_attributes=(trip_comment_attributes)
    #   trip_comment_attributes.values.each do |trip_comment_attributes|
    #     if trip_comment_attributes["comment"].present?
    #       trip_comment = TripComment.create(trip_comment_attributes)
    #       self.trip_comments << trip_comment
    #     end
    #   end
    # end

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
    before_action :redirect_user

    def new 
        @bike = Bike.new
    end

    def create
        @bike = Bike.new(bike_params)
        if(@bike.save)
            redirect_to bike_path(@bike)
        else
            render :new
        end
    end

    def edit                
        @bike = Bike.find(params[:id])        
    end

    def update        
        @bike = Bike.find(params[:id])
        
        @bike.update(bike_params)
        if(@bike)            
            redirect_to bike_path(@bike)
        else
            render :edit
        end
    end

    def show
        @bike = Bike.find(params[:id])
    end

    def images        
        @bike = Bike.find(params[:bike_id])
        @image = @bike.images.find(params[:image_id])                
    end

    def destroyImage
        @bike = Bike.find(params[:bike_id])
        @bike.images.find(params[:image_id]).destroy

        redirect_to edit_bike_path(@bike)
        
    end

    private

    def bike_params
        params.require(:bike).permit(
            :bike_name,
            :bike_type,
            :manufacturer_id,
            :biker_id,
            :stolen,
            images: []
        )
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/views/bikes/edit.html.erb
<h2>Edit new bike for <%= session[:first_name]  %></h2>

<%= form_for @bike do |f| %>
    <%= f.label :bike_name %><br>
    <%= f.text_field :bike_name %><br>
    <%= f.label :bike_type %><br>
    <%= f.text_field :bike_type %><br>
    <%= f.label :stolen %><br>
    <%= f.check_box :stolen %><br><br>
    <%= f.label :manufacturer_id %><br>
    <%= f.collection_select :manufacturer_id, Manufacturer.all, :id, :name %><br><br>

    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %><br><br>
    <%= f.submit %>
<% end %>

<h3>Images</h3>
<ul class="bike_pics">
    <% @bike.images.each do |image| %>    
        <li>
        <%= link_to( image_tag(image, :size => "200x100", :class => "thumbnail"), bikes_image_path("bike_id" => @bike, "image_id" => image))  %>        
        <%= button_to "Delete Image", bikes_image_path("bike_id" => @bike, "image_id" => image), method: :delete %>
        </li>
    <% end %>
<ul>

app/views/bikes/images.html.erb
<%= image_tag(@image)%>

app/views/bikes/new.html.erb
<h2>Create new bike for <%= session[:first_name]  %></h2>

<%= form_for @bike do |f| %>
    <%= f.hidden_field :biker_id, value: session[:user_id] %>
    <%= f.label :bike_name %><br>
    <%= f.text_field :bike_name %><br>
    <%= f.label :bike_type %><br>
    <%= f.text_field :bike_type %><br>
    <%= f.label :stolen %><br>
    <%= f.check_box :stolen %><br>
    <%= f.collection_select :manufacturer_id, Manufacturer.all, :id, :name %><br><br>

    <%= f.label :images %>
    <%= f.file_field :images, multiple: true %>
    <br><br>
    <%= f.submit %>
<% end %>

app/views/bikes/show.html.erb
<h2><%= session[:first_name]  %>'s bike</h2><br>

<% if (@bike.biker.id == session[:user_id]) %>
    <%= link_to("Edit", edit_bike_path(@bike.id))%><br>
<% end %>

Bike name: <%= @bike.bike_name %><br>
Bike type: <%= @bike.bike_type %><br>
Bike manufacturer: <%= @bike.manufacturer.name %><br>
Bike stolen: <%= @bike.stolen.to_s %><br><br>



<h3>Images</h3>
<ul class="bike_pics">
    <% @bike.images.each do |image| %>    
        <li>
        <%= link_to( image_tag(image, :size => "200x100", :class => "thumbnail"), bikes_image_path("bike_id" => @bike, "image_id" => image))  %>        
        </li>
    <% end %>
<ul>